name: Compile Resume LaTeX document
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: |
            cv.tex
            resume.tex
      - name: Checking Files
        run: ls -a && cd src && ls -a
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE.md
          files: |
            src/cv.pdf
            src/resume.pdf
          name: Download Resume
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        if: startsWith(github.ref, 'refs/tags/')
        with:
          credentials: ${{ secrets.credentials }}
          filename: "src/*.pdf"
          folderId: "19MLkW83T63CDFbVnXhbZ_6E_3CLpIGgw"
          overwrite: "true" # optional boolean