name: Compile Resume
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: "*.tex"
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md
          files: src/*.pdf
          name: Download Resume
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "src/*.pdf"
          folderId: "19MLkW83T63CDFbVnXhbZ_6E_3CLpIGgw"
          overwrite: "true" # optional boolean